version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: codeherd-be_test
          POSTGRES_HOST_AUTH_METHOD: trust
          RAILS_ENV: test
          RACK_ENV: test
    steps:
      - checkout
      - run: bundle install
      # - run:
      #     name: set up DB
      #     command: |
      #       bundle exec rake db:create db:schema:load --trace
      #       bundle exec rake db:migrate
      #     environment:
      #         DATABASE_URL: "postgres://circleci@localhost:5432/codeherd-be_test"
      - run: bundle exec rspec spec

workflows:
  heroku_deploy:
    jobs:
      - test
